<?xml version="1.0" encoding="UTF-8"?>
<!--
  Maven projet racine : gestion des stocks et réapprovisionnement des goodies
  Structure :
    - esm.gestionStocksAthletes  (application de gestion des stocks / réservations)
    - esm.reapproStocksGoodies   (application de réapprovisionnement des goodies)
-->
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>esm</groupId>
    <artifactId>esm.goodies</artifactId>
    <version>1.0.0</version>
    <packaging>pom</packaging>
    <name>Gestion des Goodies pour les Athletes</name>

    <properties>
        <maven.compiler.source>17</maven.compiler.source>
        <maven.compiler.target>17</maven.compiler.target>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    </properties>

    <modules>
        <module>gestionStocks</module>
        <module>reapproStocks</module>
    </modules>
</project>
